baseurl = "http://www.example.com"
title = "Ilya Mochalov"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ilya Mochaov"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Ilya Mochalov"
        author = "Ilya Mochaov1"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        info = "Full Stack DevOps and Magician"
        description = "John Doe's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Help"
        weight = 2.0
        url = "/help/"


    [languages.ru]
        languagename = "Русский язык"
        title = "Илья Мочалов"
        author = "Ilya Mochaov33"

        [languages.ru.params]
            description = "Strona domowa John'a Doe"
            keywords = "blog,developer,strona domowa"
            info = "Full Stack DevOps i Magik"

        [languages.ru.menu]

            [[languages.ru.menu.main]]
            name = "О мне"
            weight = 1.0
            url = "/ru/about/"

            [[languages.ru.menu.main]]
            name = "Blog"
            weight = 2.0
            url = "/ru/posts/"

    info = "Full Stack DevOps and Magician"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"